Project 3: Style core elements
crgc/microverse-awesome-books pull request #5
Opened 2021-07-07 20:34 UTC by crgc

### Features
- Used plain CSS (no framework) to style the app according to the required layout

2021-07-07 21:22 UTC, mimipeshy requested changes
## Hi Team @crgc and @eri8-9 👋🏾 👋🏾  

Good job so far!

#### Highlights

- Great UI design ✔️ 
- Good use of proper git-flow ✔️ 
- Good commit messages ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
------

2021-07-07 21:22 UTC, mimipeshy commented on css/style.css
> +  flex-direction: column;
- [ ]   Let's keep our code DRY. `display: flex` and `flex-direction: column` has been repeated more than once. To solve this you can group all classes with the same attribute together and give it one attribute eg
```
main,
.add-btn {
    display:flex
}
```

2021-07-07 21:22 UTC, mimipeshy commented on index.html
> +      <!-- <script src="js/_main_.js"></script> -->
- [ ] Kindly lets remove commented out code so that we keep the codebase clean

2021-07-08 00:44 UTC, voscarmv approved these changes
Hi @crgc , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 00:47 UTC, merged